<?php
/**
 * PHP Layout Drupal module hook definitions and module placeholder.
 */

/**
 * Implements hook_page_build().
 */
function phplayout_page_build(&$page) {
  if ($node = menu_get_object()) {

    // Fetch all layouts for the node
    $layoutIdList = db_query("select id from {layout} where node_id = ? and region is not null", [$node->nid])->fetchCol();

    if (!$layoutIdList) {
      return;
    }

    /** @var \MakinaCorpus\Layout\Storage\LayoutStorageInterface $storage */
    $storage = \Drupal::service('php_layout.storage');
    /** @var \MakinaCorpus\Layout\Render\Renderer $renderer */
    $renderer = \Drupal::service('php_layout.renderer');
    /** @var \MakinaCorpus\Drupal\Layout\Storage\Layout $layout */

    // Attempt with single pass
//     $containers = [];
//     foreach ($storage->loadMultiple($layoutIdList) as $layout) {
//       $containers[$layout->getRegion()] = $layout->getTopLevelContainer();
//     }
//     foreach ($renderer->renderAll($containers) as $region => $output) {
//       $page[$region]['layout'] = ['#markup' => $output];
//     }

    // Working multiple pass version
    foreach ($storage->loadMultiple($layoutIdList) as $layout) {
      // $page[$layout->getRegion()]['layout'] = ['#markup' => $renderer->render($layout->getTopLevelContainer())];
    }
  }
}
