<?php
/**
 * PHP Layout Drupal module hook definitions and module placeholder.
 */

use MakinaCorpus\Drupal\Layout\Form\LayoutContextEditForm;
use MakinaCorpus\Drupal\Layout\Storage\Layout;
use MakinaCorpus\Layout\Error\InvalidTokenError;
use MakinaCorpus\Layout\Grid\Item;
use MakinaCorpus\Layout\Storage\LayoutStorageInterface;

/**
 * Layout edit token get parameter name
 */
const PHP_LAYOUT_TOKEN_PARAMETER = 'layout-edit';

/**
 * Implements hook_menu().
 */
function phplayout_menu() {
  $items = [];

  // Edit callbacks for AJAX/other.
  $items['layout/ajax/add-column'] = [
    'page callback' => 'sf_dic_page',
    'page arguments' => ['php_layout.drupal_layout_controller::addColumn'],
  ];
  $items['layout/ajax/add-column-container'] = [
    'page callback' => 'sf_dic_page',
    'page arguments' => ['php_layout.drupal_layout_controller::addColumnContainer'],
  ];
  $items['layout/ajax/add-item'] = [
    'page callback' => 'sf_dic_page',
    'page arguments' => ['php_layout.drupal_layout_controller::add'],
  ];
  $items['layout/ajax/remove-column'] = [
    'page callback' => 'sf_dic_page',
    'page arguments' => ['php_layout.drupal_layout_controller::removeColumn'],
  ];
  $items['layout/ajax/remove'] = [
    'page callback' => 'sf_dic_page',
    'page arguments' => ['php_layout.drupal_layout_controller::remove'],
  ];

  // Add item form.
  $items['layout/callback/add-item'] = [
    'page callback' => 'sf_dic_page',
    'page arguments' => ['php_layout.drupal_layout_controller::addItemForm'],
  ];

  // Add item node selection autocomplete callback.
  $items['layout/callback/node-autocomplete'] = [
    'page callback' => 'sf_dic_page',
    'page arguments' => ['php_layout.drupal_layout_controller::nodeAutocomplete'],
  ];

  return $items;
}

/**
 * Implements hook_page_build().
 */
function phplayout_page_build(&$page) {
  if (arg(0) === 'node' && !arg(2) && ($node = menu_get_object())) {

    /** @var \MakinaCorpus\Layout\Storage\LayoutStorageInterface $storage */
    $storage = \Drupal::service('php_layout.storage');
    /** @var \MakinaCorpus\Layout\Controller\Context $context */
    $context = \Drupal::service('php_layout.context');

    // Fetch all layouts for the node
    $layoutIdList = db_query("select id from {layout} where node_id = ?", [$node->nid])->fetchCol();

    if ($layoutIdList) {
      $layouts = $storage->loadMultiple($layoutIdList);
    } else {
      // Create layout for node
      $layouts = [$storage->create(['node_id' => $node->nid])];
    }

    $context->add($layouts, true /* @todo access checks on each layout */);

    // Load the token after we did loaded all the layouts, to ensure that
    // their temporary equivalents attached to the token will be reloaded
    // instead.
    if (isset($_GET[PHP_LAYOUT_TOKEN_PARAMETER])) {
      try {
        $context->setCurrentToken($_GET[PHP_LAYOUT_TOKEN_PARAMETER]);
      } catch (InvalidTokenError $e) {
        // Fallback on non-edit mode
      }
    }

    /** @var \MakinaCorpus\Layout\Render\Renderer $renderer */
    $renderer = \Drupal::service('php_layout.renderer');

    // Working multiple pass version
    foreach ($context->getAll() as $layout) {
      if (!$layout instanceof Layout || !($region = $layout->getRegion())) {
        $region = 'content';
      }
      $page[$region]['layout'][$layout->getId()] = ['#markup' => $renderer->render($layout->getTopLevelContainer())];
    }

    if ($context->containsEditableLayouts()) {
      if ($context->hasToken()) {
        $path = drupal_get_path('module', 'phplayout');
        drupal_add_css($path . '/public/edit.css');
        drupal_add_js($path . '/public/edit.js');
      }

      $page['content']['layout_edit_form'] = \Drupal::formBuilder()->getForm(LayoutContextEditForm::class);
      $page['content']['layout_edit_form']['#weight'] = -1000;
    }
  }
}
